laugnage: python
sudo: false
install:
  - "pip install matplotlib"
script:
  - ./bin/pltcli ./sample_data/sin.csv ./sample_data/cos.csv --label '$\sin$' --label '$\cos$' --show-grid --x-title '$x$' --y-title '$y$' -o hoge.png
