laugnage: python
sudo: false
addons:
  apt:
    packages:
      - python-pip
      - python-matplotlib
      - python-tk
install:
  - pip install --user mkdocs
script:
  - export PATH=$PATH:$PWD/bin
  - ./build_doc.sh
