site_name: pltcli
theme: readthedocs
pages:
  - 'Introduction': index.md
  - 'Plot your csv files': 01_basic.md
  - 'Title': 02_title.md
  - 'Legend and Label': 03_label.md
  - 'Scatter': 04_scatter.md
  - 'Histogram': 05_hist.md